@baseUrl = http://localhost:3000

### Listar clientes
GET {{baseUrl}}/customer
Content-Type: application/json

### Criar clientes
POST {{baseUrl}}/customer
Content-Type: application/json  

{
  "name": "asda",
  "lastName": "gelo",
  "cpf": "67812112111",
  "phone": "1234811901",
  "zipCode": "12345678",
  "user": {
    "email": "t11@teste.com",
    "password": "11231231223"
  }
}