@baseUrl = http://localhost:3000

### Listar clientes
GET {{baseUrl}}/customer
Content-Type: application/json

### Criar clientes
POST {{baseUrl}}/customer
Content-Type: application/json  

{
  "name": "asda",
  "lastName": "gelo",
  "cpf": "67891121111",
  "phone": "12345678901",
  "zipCode": "12345678",
  "user": {
    "email": "t1o1wq12211@teste.com",
    "password": "123"
  }
}