@baseUrl = http://localhost:3000

### Listar clientes
GET {{baseUrl}}/customer
Content-Type: application/json

### Criar clientes
POST {{baseUrl}}/customer
Content-Type: application/json  

{
  "name": "asda",
  "lastName": "gelo",
  "cpf": "67890111111",
  "phone": "12345678901",
  "zipCode": "00000000",
  "user": {
    "email": "t1o1121$teste.com",
    "password": "minhasenha123"
  }
}