@baseUrl = http://localhost:3000

### Listar clientes
GET {{baseUrl}}/mechanic
Content-Type: application/json

### Criar clientes
POST {{baseUrl}}/mechanic
Content-Type: application/json  

{
  "name": "tiao"
}

